POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Leon Lucchese", 
  "email": "leon@test.com",
  "password": "senha123"
}

###
POST http://localhost:3333/session
Content-Type: application/json

{
  "email": "leon@test.com",
  "password": "senha123"
}

###
GET http://localhost:3333/me
Authorization: Bearer authToken